name: Kwiki-MindMap
version: 0.04
abstract: A Kwiki plugin that displays what's on your mind
author: Kang-min Liu (gugod@gugod.org)
license: perl
distribution_type: module
requires:
  Kwiki: 0.31
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
